(define rand
  (let ((x 1000000))
    (define generate (lambda ()
                       (set! x (random x))
                       x))
    (define (reset new-value) (begin (set! x new-value) x))
    (define (dispatch message) 
      (cond ((eq? message 'generate) 
             (generate))
            ((eq? message 'reset) 
             reset)))
  dispatch))