(define (make-account balance secret-password)
  (let ((failure-count 0))
    (define (withdraw amount)
      (set! failure-count 0)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
                 balance)
          "Insufficient funds"))
    (define (deposit amount)
      (set! failure-count 0)
      (set! balance (+ balance amount))
      balance)
    (define (dispatch n m)
      (if (eq? n secret-password)
          (cond ((eq? m `withdraw) withdraw)
                ((eq? m `deposit) deposit)
                (else (error "Unknown request: MAKE-ACCOUNT"
                             m)))
          (if (< failure-count 7) 
              (error "Incorrect password" (begin (set! failure-count (+ failure-count 1)) failure-count))
              (call-the-cops))))
    dispatch))


(define (call-the-cops) (error "We're on our way"))